### ISSUE TITLE
Automatic deployment fails for 2022.1

### ISSUE THREAD

**Issue by mu88** [vladyslav-burylov/resharper-testlinker2#7]
The automatic deployment via GitHub Actions fails atm because building on Linux fails with the following error:
```

> Task :buildSearchableOptions
Installation home directory: file:////home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2022.1/3359a42138f5a6a0343321213b46ac791240e1c4/riderRD-2022.1
System directory: file:////home/runner/work/resharper-testlinker2/resharper-testlinker2/build/idea-sandbox/system
Config directory: file:////home/runner/work/resharper-testlinker2/resharper-testlinker2/build/idea-sandbox/config
Log directory: file:////home/runner/work/resharper-testlinker2/resharper-testlinker2/build/idea-sandbox/system/log

Following output will be written to a log file /home/runner/work/resharper-testlinker2/resharper-testlinker2/build/idea-sandbox/system/log/frontend.log
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.lang.UrlClassLoader (file:/home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2022.1/3359a42138f5a6a0343321213b46ac791240e1c4/riderRD-2022.1/lib/util.jar) to field java.lang.ClassLoader.classLoaderValueMap
WARNING: Please consider reporting this to the maintainers of com.intellij.util.lang.UrlClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2022-04-20 06:15:15,672 [   1404] SEVERE - #c.i.i.ApplicationLoader - Cannot run program "/home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2022.1/3359a42138f5a6a0343321213b46ac791240e1c4/riderRD-2022.1/lib/ReSharperHost/linux-x64/dotnet/dotnet": error=13, Permission denied
java.io.IOException: Cannot run program "/home/runner/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2022.1/3359a42138f5a6a0343321213b46ac791240e1c4/riderRD-2022.1/lib/ReSharperHost/linux-x64/dotnet/dotnet": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.jetbrains.rider.protocol.ReSharperProcessBase.start(ReSharperProcessBase.kt:363)
	at com.jetbrains.rider.protocol.ReSharperProcess.<init>(ReSharperProcess.kt:232)
	at com.jetbrains.rider.protocol.ProtocolManager.k(ProtocolManager.kt:243)
	at com.jetbrains.rider.protocol.ProtocolManager.h(ProtocolManager.kt:166)
	at com.jetbrains.rider.protocol.ProtocolManager.<init>(ProtocolManager.kt:161)
	at com.jetbrains.rider.RiderApplicationLoadListener.beforeApplicationLoaded(RiderApplicationLoadListener.kt:64)
	at com.intellij.idea.ApplicationLoader.initConfigurationStore(ApplicationLoader.kt:422)
	at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt:137)
	at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 19 more
2022-04-20 06:15:15,676 [   1408] SEVERE - #c.i.i.ApplicationLoader - JetBrains Rider 2022.1  Build #RD-221.5080.235
2022-04-20 06:15:15,683 [   1415] SEVERE - #c.i.i.ApplicationLoader - JDK: 11.0.14.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-04-20 06:15:15,684 [   1416] SEVERE - #c.i.i.ApplicationLoader - OS: Linux
2022-04-20 06:15:15,830 [   1562]   WARN - j.u.prefs - Prefs file removed in background /home/runner/.java/.userPrefs/prefs.xml
2022-04-20 06:15:16,408 [   2140]   WARN - #c.i.n.i.NotificationGroupManagerImpl - Notification group Debugger event log messages is already registered (group=com.intellij.notification.NotificationGroup@1adf30c4). Plugin descriptor: PluginDescriptor(name=IDEA CORE, id=com.intellij, descriptorPath=plugin.xml, path=~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2022.1/3359a42138f5a6a0343321213b46ac791240e1c4/riderRD-2022.1/lib, version=221.5080.235, package=null, isBundled=true)
2022-04-20 06:15:16,418 [   2150]   WARN - #c.i.n.i.NotificationGroupManagerImpl - Notification group Rider Remote Debugger: Upload Error is already registered (group=com.intellij.notification.NotificationGroup@4581d18d). Plugin descriptor: PluginDescriptor(name=IDEA CORE, id=com.intellij, descriptorPath=plugin.xml, path=~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2022.1/3359a42138f5a6a0343321213b46ac791240e1c4/riderRD-2022.1/lib, version=221.5080.235, package=null, isBundled=true)
2022-04-20 06:15:16,422 [   2154]   WARN - #c.i.n.i.NotificationGroupManagerImpl - Notification group Xcode settings warnings is already registered (group=com.intellij.notification.NotificationGroup@6ff529ea). Plugin descriptor: PluginDescriptor(name=IDEA CORE, id=com.intellij, descriptorPath=plugin.xml, path=~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2022.1/3359a42138f5a6a0343321213b46ac791240e1c4/riderRD-2022.1/lib, version=221.5080.235, package=null, isBundled=true)
2022-04-20 06:15:16,423 [   2155]   WARN - #c.i.n.i.NotificationGroupManagerImpl - Notification group Xamarin launch is already registered (group=com.intellij.notification.NotificationGroup@1f3677d0). Plugin descriptor: PluginDescriptor(name=IDEA CORE, id=com.intellij, descriptorPath=plugin.xml, path=~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2022.1/3359a42138f5a6a0343321213b46ac791240e1c4/riderRD-2022.1/lib, version=221.5080.235, package=null, isBundled=true)
2022-04-20 06:15:16,423 [   2155]   WARN - #c.i.n.i.NotificationGroupManagerImpl - Notification group ASP.NET Core Certificate Notifications is already registered (group=com.intellij.notification.NotificationGroup@7c8c2de2). Plugin descriptor: PluginDescriptor(name=IDEA CORE, id=com.intellij, descriptorPath=plugin.xml, path=~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2022.1/3359a42138f5a6a0343321213b46ac791240e1c4/riderRD-2022.1/lib, version=221.5080.235, package=null, isBundled=true)
2022-04-20 06:15:16,479 [   2211]   WARN - #c.i.i.DebugAttachDetector - Unable to start DebugAttachDetector, please add `--add-exports java.base/jdk.internal.vm=ALL-UNNAMED` to VM options
```

But I can build the plugin locally on my Windows machine and everything works fine.

@vladyslav-burylov Could you please do the publishing manually?
I will handle the automatic deployment.

**Comment by vladyslav-burylov** [comment]
Hi @mu88 - thanks for supporting it! Do you still need to still need help with deployment?

**Comment by vladyslav-burylov** [comment]
Alright, it seems it works - I have received "new version pending approval" alert from Jet Brains just now

**Comment by mu88** [comment]
Hi @vladyslav-burylov - sorry for the back and forth 🙈 honestly I didn't expect to find a solution so quickly! Now everything should be good - hopefully 🤞🏻
